apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-cni
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: 1.22.3
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: istiod-values
      valuesKey: values.yaml
  wait: true

