apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: istio-system
spec:
  interval: 5m
  dependsOn:
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: kiali-server
      version: 2.16.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: kiali-values
      valuesKey: values.yaml

