apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: cni
      version: 1.22.3
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: istio-cni-values
      valuesKey: values.yaml
  

