apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-ambient
  namespace: ambient
spec:
  interval: 5m
  chart:
    spec:
      chart: ambient
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio-official
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: ambient-values
      valuesKey: values.yaml

